# ansible-playbook -e device=<your-input> -e service=<service-input> -e remote_user=<remote-user> <directory-jump>/restart-service.yml
# ansible-playbook -e device=127.0.0.1 -e service=httpd remote_user=john ../playbooks/restart-service.yml

- name: Restart service with host using external variable
  hosts: "{{ device }}"
  remote_user: "{{ remote_user }}"
  tasks:
    - name: Restarting {{ service }}.
      ansible.builtin.service:
        name: "{{ service }}"
        state: restarted