name: Test App Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy-staging:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-node@v2
      with:
        node-version: '16.13.1'
    - uses: actions/checkout@v2
    - name: Install Dependencies
      run: npm install
    - name: Install Rsync
      run: sudo apt update && sudo apt install rsync
    - name: Create rsync exclude.txt
      run: |
        echo -e '.git' >> exclude-list.txt
        echo -e '.env.example' >> exclude-list.txt
        echo -e '.gitignore' >> exclude-list.txt
        echo -e '.idea' >> exclude-list.txt
        echo -e 'exclude-list.txt' >> exclude-list.txt
    - name: Adding Host key to know_hosts file
      run: mkdir -p ~/.ssh && ssh-keyscan -H ${{ secrets.SERVER_HOSTNAME }} >> ~/.ssh/known_hosts
    - name: Debug
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOSTNAME }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: ls
    - name: Stop docekr compose services over SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOSTNAME }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: cd tests && docker-compose down
    - name: Deploy to staging Server via Rsync
      uses: AEnterprise/rsync-deploy@v1.0
      env:
          DEPLOY_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: "-azvW --delete --exclude-from exclude-list.txt"
          SERVER_PORT: ${{ secrets.SSH_PORT }}
          FOLDER: "./"
          SERVER_IP: ${{ secrets.SERVER_HOSTNAME }}
          USERNAME: ${{ secrets.SSH_USERNAME }}
          SERVER_DESTINATION: ${{ secrets.DEPLOY_PATH }}
    - name: Start all services over SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOSTNAME }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: cd tests && docker-compose up --build -d
